[build]
  command = "npm run build"
  publish = "out"

# Important: skip the Next plugin so we can use plain static export
[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NEXT_DISABLE_ESLINT = "1"
  NEXT_DISABLE_TYPECHECK = "1"
  NEXT_TELEMETRY_DISABLED = "1"
# Static export for Netlify
[build]
  command = "npm run build"
  publish = "out"
